apps/summon-safe/project.json
apps/summon-safe/src/assets/manifest.json
apps/summon-safe/src/components/AppFooter.tsx
apps/summon-safe/src/index.html
apps/summon-safe/src/views/Daos.tsx
libs/moloch-v3-data/src/utils/index.ts

Fix manifest + other metadata to make the app readable through the Gnosis Safe App

Fix summon safe app

---

apps/admin/src/components/MemberProfileAvatar.tsx
apps/admin/src/components/Profile.tsx
apps/admin/src/pages/Member.tsx
apps/admin/src/pages/Members.tsx
libs/ui/src/components/organisms/MemberCard/MemberCard.tsx

Related https://github.com/HausDAO/daohaus-monorepo-deprecated/issues/725
This PR finishes adding MemberCard to user entities displayed on Member Profile page

Add member card for entities shown in Member profile page

---

apps/summon/src/layouts/MemberSegment.tsx

https://github.com/HausDAO/daohaus-monorepo-deprecated/issues/369
Updated placeholder for members stake on summoner form
n/a

Update voting stake placeholder

---

.husky/pre-push

Update husky to use develop as base
NA
**These shouldn't really apply anymore now that we have Huskey set up**

Set base as develop

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

bumps all lib version

---

apps/admin/src/pages/DaoContainer.tsx

n/a
- memoizes the env variable assignment

fixes extra render issues

---

libs/form-builder/src/components/formFooter.tsx

NA
General fixes from Testing session
- Button size on forms
NA

Updated button at bottom of Form to be normal size

---

apps/admin/src/components/AddSafeForm.tsx
apps/admin/src/components/ManageDelegate.tsx
apps/admin/src/pages/FormTest.tsx
apps/admin/src/pages/NewProposal.tsx
apps/admin/src/pages/RageQuit.tsx
apps/admin/src/pages/UpdateSettings.tsx

https://github.com/HausDAO/monorepo/issues/104
Fixes form submitting on wrong DAO chain
Uses formbuilder targetNetwork prop

add daochain to target network props

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

version bumps

---

apps/admin/src/components/customFields/MultisendActions.tsx
libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/connect/src/components/DaoHausNav/DaoHausNav.styles.ts
libs/connect/src/components/DaoHausNav/DaoHausNav.tsx
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/data-fetch-utils/project.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/profile-data/package.json
libs/profile-data/project.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

version bump and project.json fixes

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-data/src/vaults.ts
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

updates versions and ethers imports again

---

libs/ui/src/components/molecules/LoadingButton/index.ts

NA
Fixed import for loading button
NA

Updated export for Loading Button

---

libs/ui/package.json

add react-router-dom

---

package.json
yarn.lock

Fixes Wallet connect issues by rolling it back. 
Will need to make a ticket for using the new Wallet Connect API as mentioned here. 
https://github.com/WalletConnect/walletconnect-monorepo/issues/1686

Wallet connect fix

---

apps/admin/src/components/proposalCards/Unsponsored.tsx

Fixes #158 
Sponsor proposal is disabled if a member has delegated his voting power and does not have any voting delegated to him
None

Fix delegate sponsor proposal for members with delegated voting power

---

apps/admin/src/App.tsx
apps/admin/src/Routes.tsx
apps/admin/src/main.tsx
libs/connect-context/src/ConnectContext.tsx
libs/connect/src/HausConnectContext.tsx
libs/ui/src/components/atoms/Tag/Tag.styles.ts
libs/ui/src/components/atoms/Tag/Tag.tsx
libs/ui/src/components/atoms/Tag/Tag.types.ts
libs/ui/src/types/formAndField.ts

Fixes
- https://github.com/HausDAO/monorepo/issues/151
- https://github.com/HausDAO/monorepo/issues/160
-https://github.com/HausDAO/monorepo/issues/156
90min. 
- Everything in the mentioned tickets + addred a value prop to all fields. 
NA

Small app fixes

---

apps/admin/src/legos/form.ts
apps/admin/src/legos/tx.ts
apps/admin/src/pages/FormTest.tsx
apps/admin/src/utils/constants.ts
libs/abis/src/abi/gnosisModule.json

n/a
- new form and tx lego 
- added a prop type
n/a

adds signer to safe prop

---

apps/admin/src/components/AddSafeForm.tsx
apps/admin/src/components/ManageDelegate.tsx
apps/admin/src/components/proposalCards/HasNotVoted.tsx
apps/admin/src/components/proposalCards/ReadyForProcessing.tsx
apps/admin/src/components/proposalCards/Unsponsored.tsx
apps/admin/src/pages/NewProposal.tsx
apps/admin/src/pages/RageQuit.tsx
apps/admin/src/pages/UpdateSettings.tsx
libs/form-builder/src/components/FormBuilder.tsx
libs/tx-builder/src/TXBuilder.tsx
libs/tx-builder/src/utils/polling.ts
libs/tx-builder/src/utils/txBuilderUtils.ts
libs/utils/src/types/legoTypes.ts
yarn.lock

- https://github.com/HausDAO/monorepo/issues/154
- https://github.com/HausDAO/monorepo/issues/155
All of the above changes in the tickets, plus: 
- Custom polling
- extra data sent through LifeCycleFns callbacks
```ts
export type TXLifeCycleFns = {
onRequestSign?: () => void;
onTxHash?: (txHash: string) => void;
onTxError?: (error: unknown) => void;
onTxSuccess?: (
txReceipt: ethers.providers.TransactionReceipt,
txHash: string,
appState: ArbitraryState
) => void;
onPollStart?: () => void;
onPollError?: (error: unknown) => void;
onPollSuccess?: (
result: any,
txReceipt: ethers.providers.TransactionReceipt,
appState: ArbitraryState
) => void;
}; 
```
and all of these lifecycle fns are now available through form Builder
```ts
return (
<FormBuilder
form={formLego}
customFields={CustomFields} …
```

Tx builder upgrades

---

apps/admin/src/components/customFields/TributeInput.tsx

fixes: https://github.com/HausDAO/monorepo/issues/177
needed to add the token decimals on the setValueAs
```ts
toBaseUnits(val, tokenData?.decimals)
```

fixes towei issue on tribute input field

---

apps/admin/src/components/VaultMenu.tsx
apps/admin/src/components/customFields/MultisendActions.tsx
apps/admin/src/legos/form.ts
apps/admin/src/legos/tx.ts

Closes #173 
Add a new form and tx lego to enable multicall tx builder proposals to sidecar vaults. A menu option on on the vaults page allows users to open the proposal form
None

enable mulicall tx builder for sidecar vaults

---

apps/admin/src/pages/ProposalDetails.tsx
libs/tx-builder/src/utils/decoding.ts

None
It allows catching an exception when a 3rd party app does not craft the multisend tx accordingly. Sample proposal https://admin.daohaus.fun/#/molochV3/0x5/0xe1db4e8b5f4eabba128be487b5f17dacbcde470f/proposals/8
None

Handle proposal decoding errors if it's not properly crafted as a multisend action

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json
libs/utils/project.json

release version bump

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json
libs/utils/project.json

one more bump

---

apps/admin/src/components/ProposalHistoryCard.tsx

Closes #201 
Use dao parameters instead of provider context to craft the link to open the proper network explorer
None

Fix explorer link on proposal history

---

libs/form-builder/src/FormBuilder.tsx
libs/form-builder/src/components/formFooter.tsx
libs/tx-builder/src/TXBuilder.tsx

Closes #197 
Adds a new status in FormBuilder so an error is thrown if TxBuilder context is missing
None

Throw error in formbuilder if txbuilder context is missing

---

libs/keychain-utils/src/endpoints.ts

Update endpoints for Gnosis Safe Tx API

---

libs/moloch-v3-hooks/src/hooks/index.ts
libs/moloch-v3-hooks/src/hooks/useProfile.tsx

Added in useProfile hook from Jords branch
NA

Added useProfile hook from Jord's branch for others to use.

---

apps/admin/src/components/ProposalCardOverview.tsx
apps/admin/src/components/ProposalDetailsGuts.tsx

NA - Reported in Discord
Added word break to allow for long addresses to break to new line.
NA

Fixed descriptions for very long strings aloowing to break on the word.

---

libs/ui/src/components/organisms/MemberCard/MemberCard.stories.tsx

Commented out the story that was adding react router to the package

---

apps/admin-new/src/pages/Proposals.tsx
libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-macro-ui/package.json
libs/moloch-v3-macro-ui/src/components/ProposalCard/ProposalCard.tsx
libs/moloch-v3-macro-ui/src/components/ProposalList/ProposalList.tsx
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

macro release

---

apps/admin-new/src/components/CancelProposal.tsx
apps/admin-new/src/pages/Proposal.tsx
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/ManageDelegate.tsx

#239 
#209 
- Add CancelProposal button
- Enable ManageDelegate form legos on macro component
None

macros misc

---

apps/admin-new/src/pages/Member.tsx
apps/admin-new/src/pages/Members.tsx
libs/moloch-v3-macro-ui/src/components/MemberList/MemberList.styles.ts
libs/moloch-v3-macro-ui/src/components/MemberList/MemberList.tsx
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/MemberProfile.tsx
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/MemberProfileAvatar.tsx
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/MemberProfileCard.styles.ts
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/MemberProfileCard.tsx
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/MemberProfileMenu.tsx
libs/utils/src/utils/general.ts

#239 
#209 
Adds minor improvements to member UI macros
None

UI improvements on member macros

---

apps/admin/src/legos/tx.ts

None
Avoid using `ENCODED_0X0_DATA` as it makes proposals to fail during execution
None

Remove ENCODED_0X0_DATA

---

apps/admin/src/components/customFields/TributeInput.tsx
libs/moloch-v3-fields/src/fields/TributeInput.tsx

https://discord.com/channels/709210493549674598/740299170589704364/1086012964622049301
Adds a missing format parameter 
None

Fix missing format param

---

apps/admin/src/components/Profile.tsx
apps/admin/src/pages/Member.tsx
apps/admin/src/utils/cacheProfile.ts
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/MemberProfile.tsx
libs/profile-data/src/utils/transformers.ts
libs/ui/src/components/molecules/ProfileAvatar/ProfileAvatar.tsx

None
Fix profile avatars not being displayed on the member page
None

Profile avatars not being displayed on member page

---

.github/workflows/ci_develop.yaml
.github/workflows/ci_main.yaml

n/a
- adds extra block explorer keys to workflows
n/a

adds env copy into workflows

---

apps/admin-new/src/pages/Proposal.tsx
apps/admin-new/src/pages/Proposals.tsx
libs/moloch-v3-macro-ui/src/components/DaoSettings/DaoSettings.styles.ts
libs/moloch-v3-macro-ui/src/components/ProposalActionData/ProposalActionData.tsx
libs/moloch-v3-macro-ui/src/components/ProposalActionData/ProposalWarning.tsx
libs/moloch-v3-macro-ui/src/components/ProposalCard/ProposalCard.tsx
libs/moloch-v3-macro-ui/src/components/ProposalCard/ProposalCardOverview.tsx
libs/moloch-v3-macro-ui/src/components/ProposalDetails/MemberDataPoint.tsx
libs/moloch-v3-macro-ui/src/components/ProposalDetails/ProposalAdditionalDetails.tsx
libs/moloch-v3-macro-ui/src/components/ProposalDetails/ProposalDetails.tsx
libs/moloch-v3-macro-ui/src/components/ProposalDetails/ProposalDetailsContainer.tsx
libs/moloch-v3-macro-ui/src/components/ProposalDetails/index.ts
libs/moloch-v3-macro-ui/src/components/ProposalList/ProposalList.tsx
libs/moloch-v3-macro-ui/src/utils/proposalDetailsHelpers.ts

n/a - from another project
- Additional data display int he proposal details
- decodes and displays data for tribute, funding and mintshares/loot proposals
n/a

gets additonal data in place for funding, tribute and mint proposals

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

https://github.com/HausDAO/monorepo/releases/tag/v0.1.29

version bump

---

libs/moloch-v3-macro-ui/src/components/ProposalActionData/ProposalActionData.tsx
libs/moloch-v3-macro-ui/src/components/ProposalDetails/ProposalDetails.styles.ts
libs/moloch-v3-macro-ui/src/utils/proposalDetailsHelpers.ts

n/a
macro-ui
- adjust placement of loading spinner on action data
- change order of additional data on some proposals
n/a

moves some additional details proposal fields around

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

release 0.1.31
https://github.com/HausDAO/monorepo/releases/tag/v0.1.31

bump version

---

apps/admin-new/src/pages/FormTest.tsx
apps/admin/src/components/proposalCards/ReadyForProcessing.tsx
libs/moloch-v3-legos/src/form.ts
libs/moloch-v3-macro-ui/src/components/ProposalCard/ReadyForProcessing.tsx
libs/tx-builder/src/utils/overrides.ts
libs/tx-builder/src/utils/txBuilderUtils.ts
libs/utils/src/types/legoTypes.ts

n/a
- adds `staticOverrides` to txlego
- improves `processOverrides` in txbuilder to process args in the overrides object or in staticOverrides
- updates so it handles proposalOffering value under the hood
- updates the processProposal transaction to use staticArgs 
n/a

implements more robust overrides and staticOverrides

---

libs/tx-builder/src/utils/contractHelpers.ts
package.json
yarn.lock

upgrade ts and adjustfindTargetAddress helper

---

libs/tx-builder/src/TXBuilder.tsx
libs/tx-builder/src/utils/txBuilderUtils.ts

integrate viem into trx builder and utils

Get signal proposal working

---

apps/admin/src/legos/tx.ts
apps/admin/src/utils/fieldHelpers.ts
apps/summon-safe/src/utils/common.ts
apps/summon/src/utils/common.ts
libs/contract-utils/src/lib/estimate-util.ts
libs/contract-utils/src/lib/types.ts
libs/moloch-v3-fields/src/utils/approveToken.ts
libs/moloch-v3-fields/src/utils/walletConnect.tsx
libs/moloch-v3-legos/src/tx.ts
libs/utils/src/types/contract.ts
libs/utils/src/types/index.ts
libs/utils/src/types/viem.ts

https://github.com/HausDAO/monorepo/issues/339
various updates to bigint

Wc upgrade bigint

---

libs/contract-utils/src/lib/encoding-utils.ts
libs/contract-utils/src/lib/moloch-v3-contract.ts
libs/contract-utils/src/lib/types.ts
libs/tx-builder/src/utils/decoding.ts

a few small changes for migrating ethers

remove byteslike from ethers

---

libs/tx-builder/src/utils/txBuilderUtils.ts

None
Fixes `TypeError: Cannot read properties of undefined (reading 'request')` error when user uses a non-browser-injected wallet provider like WalletConnect
None

Fix getting the current wallet client to process tx requests

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

https://github.com/HausDAO/monorepo/releases/tag/v0.2.0-alpha

another alpha release for testing

---

libs/form-builder-base/src/components/FormBuilderFactory.tsx
libs/moloch-v3-macro-ui/src/components/ProposalCard/ProposalCardOverview.tsx
libs/ui/src/components/atoms/Input/Input.tsx
libs/ui/src/components/atoms/Progress/Progress.styles.ts
libs/ui/src/components/atoms/Progress/Progress.tsx
libs/ui/src/components/molecules/WrappedFileInput/WrappedFileInput.tsx
libs/ui/src/components/molecules/WrappedInput/WrappedInput.tsx
libs/ui/src/components/molecules/WrappedSelect/WrappedSelect.tsx

n/a
- allowLinks to $allowLinks on a styled div
error seen in 3rd party app:

properly pass allowlinks to styled component

---

libs/ui/src/components/molecules/WrappedFileInput/WrappedFileInput.tsx
libs/ui/src/components/molecules/WrappedInputSelect/WrappedInputSelect.tsx
libs/ui/src/components/molecules/WrappedSelect/WrappedSelect.tsx
libs/ui/src/components/molecules/WrappedTextArea/WrappedTextArea.tsx

n/a
- fixes the rest of the ...rest deprecation on wrapped inputs
- removes the onChange from file input and select
n/a

fixes the wrapped input onChange and adjusts the other wrapped inputs

---

libs/ui/src/components/atoms/Typography/Typography.tsx
libs/ui/src/theme/global/font.ts
libs/ui/src/types/theming.ts

n/a
- new font in theme
- type update
- add new font to ahh H elements in UI
n/a

adds new prop to font in theme and adjusts H-family in typography

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/ui/src/theme/atoms/index.ts
libs/ui/src/theme/global/index.ts
libs/ui/src/theme/index.ts
libs/utils/package.json

n/a
- ui import updates
- version bump
n/a

fixes some exports in ui and bumps the version

---

libs/ui/src/components/atoms/Input/Input.styles.ts
libs/ui/src/components/atoms/Label/Label.styles.ts
libs/ui/src/components/atoms/Select/Select.styles.ts
libs/ui/src/components/atoms/TextArea/TextArea.styles.ts
libs/ui/src/components/layouts/FormSegment/FormSegment.styles.tsx
libs/ui/src/components/layouts/FormSegment/FormSegment.tsx
libs/ui/src/components/layouts/FormSegment/FormSegment.types.ts
libs/ui/src/theme/theme.ts
libs/ui/src/types/theming.ts

n/a
- some field spacing
- 
n/a

optional divider in form segment

---

.github/workflows/ci_main.yaml
libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

https://github.com/HausDAO/monorepo/releases/tag/v0.2.0

version bump and gh action update

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

[release 0.2.1](https://github.com/HausDAO/monorepo/releases/tag/untagged-0fd2e36983a661ee1888)

version bump to 0.2.1

---

libs/keychain-utils/src/endpoints.ts

Adding an optional polygon pos fallback
Update HAUS_RPC and .env smaple

add an alachemy optional rpc fallback

---

libs/connect-context/src/Connect.tsx
libs/utils/src/utils/viem.ts

more retries

---

libs/moloch-v3-macro-ui/src/components/DaoOverview/DaoProfile.tsx

n/a
fixes use param in macro-ui
n/a

fixes another useParams

---

apps/admin/src/components/AddSafeForm.tsx
libs/connect/src/components/DHLayout/DHLayout.tsx
libs/moloch-v3-fields/src/fields/WalletConnectLink.tsx
libs/moloch-v3-macro-ui/src/components/DaoOverview/DaoProfile.tsx

None
- Avoid useParams and employ useCurrentDao hook instead
- Fix missing parameter on DaoHausNavMenu
None

Misc fixes

---

libs/tx-builder/src/utils/constants.ts
libs/tx-builder/src/utils/multicall.ts

fixes #422 
Creates a new gas multiplier constant and bumps it up ~50%, from 2 to 3
NA
- [X ] Critical lint errors are resolved
- [X ] App runs locally
- [X ] App builds locally (run the build command for _any impacted package_ and check for any errors before the PR)

increase gas buffer multiplier and add constant

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

https://github.com/HausDAO/monorepo/releases/tag/v0.3.0

Release v0.2.4

---

apps/summon-safe/src/app/App.tsx
apps/summon-safe/src/components/RecordsDataTable.tsx
apps/summon-safe/src/components/SwitchText.tsx
apps/summon-safe/src/index.html
apps/summon-safe/src/main.tsx
apps/summon-safe/src/utils/common.ts
apps/summon-safe/src/utils/modules.ts
apps/summon-safe/src/utils/txHelpers.ts
apps/summon-safe/src/utils/types.ts
apps/summon-safe/src/views/Daos.tsx
apps/summon-safe/src/views/ModuleMarket.tsx
apps/summon-safe/src/views/SummonForm.tsx
apps/summon-safe/src/views/WizardForm.tsx
package.json
yarn.lock

None
Implements a Modules Market view and setup wizard to allow a Safe to install specialized DAOHaus modules like CookieJar
- @safe-global/safe-apps-react-sdk@^4.7.0

Add modules market to summon-safe app

---

libs/utils/src/constants/proposals.ts

#452
anther temporary work around for gas estimation issues. Update the processing addition to a higher value
none

temporary increase of processing gas addition until, needs more research

---

apps/summon/src/layouts/StakeTokenSegment.tsx
libs/utils/src/constants/summoning.ts

#455 
Allow token symbols to be 20 characters
None

increase min length of token symbols on summoner form

---

libs/moloch-v3-macro-ui/src/components/ProposalDetails/ProposalDetails.tsx

fixes #445
Makes the markdown element more readable with a styled wrapper
none

styles to make proposal details more readable

---

apps/summon-safe/src/utils/modules.ts

None
Update CookieJar module addresses
None

Update cookie jar contracts on summon-safe app

---

libs/ui/src/components/atoms/index.ts

export Radio from UI

---

.github/workflows/ci_develop.yaml
.github/workflows/ci_main.yaml
libs/keychain-utils/src/endpoints.ts
libs/moloch-v3-macro-ui/src/components/MemberList/MemberList.tsx

fixes base rpc

---

libs/abis/package.json
libs/connect-context/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/data-fetch-utils/package.json
libs/form-builder-base/package.json
libs/form-builder/package.json
libs/keychain-utils/package.json
libs/moloch-v3-data/package.json
libs/moloch-v3-fields/package.json
libs/moloch-v3-hooks/package.json
libs/moloch-v3-legos/package.json
libs/moloch-v3-macro-ui/package.json
libs/profile-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json
libs/wizard-form-builder/package.json
package.json

updated package.jsons to include a link to the repo. this is to qualify for tea and allow users to find repo from package managers
NA
Updated the package.json files to include references to the monorepo.
NA

fix(package.json):

---

libs/moloch-v3-fields/src/fields/EpochDatePicker.tsx
libs/moloch-v3-fields/src/fields/MarkdownField.tsx

n/a
- markdown field bg color loaded from the theme
n/a

adds theme color to markdown bg

---

libs/tx-builder/src/utils/multicall.ts

None
Fix tx ordering issues when using the multicall tx builder proposal
None

Fix multicall tx ordering

---

libs/keychain-utils/src/endpoints.ts

new default base rpc

---

apps/admin/src/components/CancelProposal.tsx

#520 
new copy on the tooltip
n/a

tooltip copy update

---

libs/moloch-v3-hooks/src/hooks/useConnectedMember.tsx
libs/moloch-v3-hooks/src/hooks/useDaoData.tsx
libs/moloch-v3-hooks/src/hooks/useDaoMember.tsx
libs/moloch-v3-hooks/src/hooks/useDaoMembers.tsx
libs/moloch-v3-hooks/src/hooks/useDaoProposal.tsx
libs/moloch-v3-hooks/src/hooks/useDaoProposals.tsx
libs/moloch-v3-hooks/src/hooks/useDaoRecords.tsx
libs/moloch-v3-macro-ui/src/components/DaoSettings/ShamanList.tsx

#521 519
updates to hooks and dao data queries where needed.
n/a

fixes queries if dao address isn't lowercase

---

libs/form-builder/src/FormBuilder.tsx
libs/ui/src/components/molecules/Dialog/Dialog.styles.ts
libs/ui/src/components/molecules/Dialog/Dialog.tsx

None
* FormBuilder: include `submitButtonText` from Form definition 
* Minor spelling fixes in the code
None

Minor misc fixes

---

libs/moloch-v3-fields/src/config/fieldConfig.ts
libs/moloch-v3-fields/src/fields/TransferTokens.tsx
libs/moloch-v3-fields/src/fields/index.ts
libs/moloch-v3-legos/src/fields.ts
libs/moloch-v3-legos/src/form.ts
libs/moloch-v3-legos/src/tx.ts
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/ManageTokens.tsx
libs/moloch-v3-macro-ui/src/components/MemberProfileCard/MemberProfileMenu.tsx

#525 
Adds a transfer tokens tx modal to allow a connected dao member to transfer shares/loot tokens to a recipient (if tokens are transferrable)
None

add transfer dao tokens tx modal

---

.github/ISSUE_TEMPLATE/config.yml
libs/ui/src/components/molecules/Banner/Banner.tsx

adjust discord links

---

libs/moloch-v3-data/src/vaults.ts

removes token spam filter
