HausDAO/monorepo

apps/admin/src/Routes.tsx

Quick fix to remove an infinite loop that happens when the admin app opens (root) and tries to redirect to Home view with connected account

Admin - Fix infinite loop on navigate

---

libs/abis/package.json
libs/connect/package.json
libs/contract-utils/package.json
libs/form-builder/package.json
libs/moloch-v3-context/package.json
libs/moloch-v3-data/package.json
libs/tx-builder/package.json
libs/ui/package.json
libs/utils/package.json

fixes: https://github.com/HausDAO/daohaus-monorepo-deprecated/issues/583
- version bumps

version bump

---

apps/admin/src/components/proposalCards/ActionPrimitives.tsx
apps/admin/src/components/proposalCards/ReadyForProcessing.tsx
apps/admin/src/utils/constants.ts
libs/utils/src/utils/gas.ts
libs/utils/src/utils/index.ts

fixes https://github.com/HausDAO/daohaus-monorepo-deprecated/issues/903
- adds gas estimate calc helpers and displays
- small layout changes

adjusts gas estimate wording and layout

---

apps/admin/src/legos/form.ts
libs/form-builder/src/components/SegmentRender.tsx

None
Fix field typings errors when using `formSegment`. Changes avoid having to use `@ts-expect-error: ...` comments on form field definitions
None

Fix field typings when passed to formSegment

---

apps/admin/src/Routes.tsx
apps/summon/src/app/App.tsx

fixes: https://github.com/HausDAO/daohaus-monorepo-deprecated/issues/1050
- removes banner

removes banner

---

apps/admin/src/pages/Members.tsx
libs/utils/src/utils/general.ts

Fromwei crashes when it receives an exponential (ex. 2.343 e+21)
SharesDelegatedToMember returns an exponential when it calculates a high share amt. 
This causes a crash on admin
https://admin.daohaus.fun/#/molochv3/0x5/0xc035dd7cda32ae73f0f306ed56658527aad47648/members
Fixed it by checking if the number is unsafe and converting to big int. 
We may need to do this with the rest of our conversion functions. 
--

fix exponential overload error

---

apps/admin/src/legos/contracts.ts
apps/admin/src/legos/tx.ts
apps/admin/src/pages/DaoOverview.tsx
libs/tx-builder/src/utils/args.ts
libs/tx-builder/src/utils/multicall.ts
libs/utils/src/types/legoTypes.ts

- No issue. Based on an ongoing need in Single DAO apps. 
Discussed adding this to EthDenver tooling scope w/ Sam. 
Creates a separate argType that decouples multisend calls from Baal proposals. 
This will not work on its own. Because of the delegateCall guard on the multisend, we may need to make changes on the contract side. 
https://github.com/safe-global/safe-contracts/blob/main/contracts/libraries/MultiSend.sol#L27
90 mins

Generic multisend argtype

---

apps/admin/src/components/ActionDisplay.tsx
apps/admin/src/components/customFields/MultisendActions.tsx
libs/form-builder/src/components/CoreFieldLookup.ts
libs/form-builder/src/components/TupleObject.tsx
libs/utils/src/utils/typeguards.ts
libs/utils/src/utils/validation.ts

Closes #153 
implements Object arg type on formbuilder so it is possible to create form Txs & make contract calls to methods that include Structs (tuple type) as parameters
None

Add object argtype to formbuilder

---

apps/admin/src/components/MemberProfileAvatar.tsx
apps/admin/src/components/ProposalCardOverview.tsx
apps/admin/src/pages/Member.tsx
apps/admin/src/utils/cacheProfile.ts
libs/connect-context/src/ConnectContext.tsx
libs/connect-context/src/utils/contextHelpers.ts
libs/profile-data/src/profile.ts
libs/profile-data/src/types/ens.types.ts

Fixes #186 
Apparently, it's no that easy to identify the main ENS name from an address using the subgraph. Going through the ENS docs, I find out how it uses [Reverse Resolution](https://docs.ens.domains/dapp-developer-guide/resolving-names#reverse-resolution) using a special purpose domain to set the primary ENS name a.k.a  main reverse record. The recommended approach is to use an `etherjs` provider and call `lookupAddress`, otherwise seems that we need to manually concatenate `.${address}.addr.reverse`, `namehash` it and look for the resolver in the subgraph.
I used the recommended approach to fetch the main ENS record. If not found, it fallbacks to query the subgraph for the first non-expired ens domain registered by an account address.
None
Before making your PR, please check the …

Use reverse resolution to fetch main ENS name from address

---

apps/admin/src/components/customFields/TributeInput.tsx

None
Fixes units being displayed within the max tribute button when a user token balance has a large amount of decimals
None

Truncate units display on max tribute button

---

libs/tx-builder/src/utils/args.ts
libs/utils/src/types/legoTypes.ts

Closes #196
Add template arg type to form builder so string template params can be defined within a tx lego. Any app state variable should be enclosed in curly braces e.g. 'Send {.formValues.value} ETH'
None

Add template arg type to form builder

---

apps/admin-new/src/fonts.css
apps/admin-new/src/main.tsx
libs/ui/src/components/atoms/Button/Button.styles.ts
libs/ui/src/components/atoms/Input/Input.styles.ts
libs/ui/src/components/atoms/Label/Label.styles.ts
libs/ui/src/components/atoms/Link/Link.styles.ts
libs/ui/src/components/atoms/Select/Select.styles.ts
libs/ui/src/components/atoms/Switch/Switch.styles..ts
libs/ui/src/components/atoms/TextArea/TextArea.styles.ts
libs/ui/src/components/atoms/Typography/Typography.tsx
libs/ui/src/styled.d.ts
libs/ui/src/styled.ts
libs/ui/src/theme/HausThemeContext.tsx
libs/ui/src/theme/component/fieldFamily.ts
libs/ui/src/theme/global/globalStyles.ts
libs/ui/src/theme/theme.ts
libs/ui/src/types/theming.ts

Closes #170 
Update theme context & underlying properties to allow custom fonts per App. Changes introduced in this PR would also enable dApp developers to override other theme properties in the future.
None

Enable customs fonts

---

libs/form-builder/src/FormBuilder.tsx

Currently, using the FormBuilder allows you to disable polling lifecycle functions however the feedback in the UI shows the `Please wait for subgraph to sync` message and a spinner next to `Transaction Success`:
Show proper messages `onTxSuccess` if `tx.disablePoll` is true
None

Fix form success message if poll is disabled

---

apps/admin-new/src/main.tsx
apps/admin-new/src/theme.tsx
libs/ui/src/styled.d.ts
libs/ui/src/styled.ts
libs/ui/src/types/theming.ts

Closes #169 
Allow external apps to override & customize UI theme colour
None

Enable UI theme color customization

---

apps/admin/src/components/customFields/ProposalOffering.tsx
libs/moloch-v3-fields/src/fields/ProposalOffering.tsx

proposalOffering and connectedMember.shares are strings so can not be compared as big numbers
NA

cast dao.proposalOffering to Number for gt comparison

---

apps/admin/src/components/customFields/MultisendActions.tsx
libs/moloch-v3-fields/src/fields/MultisendActions.tsx

None
https://discord.com/channels/709210493549674598/908738422666063892/1113550990994591815
Add a customData toggle on multisend action items so the user can specify custom hex data or no data (0x) for sending native tokens only to a contract recipient
None

multisend actions: enable custom data + send native token only

---

libs/tx-builder/src/utils/multicall.ts
libs/utils/src/types/legoTypes.ts

#327 
- Instead of calling `client.estimateGas` using `from -> safe address`, proposal actions are now wrapped on a `execTransactionFromModule` and called by the baal module. It removes some edge cases where the `estimateGas` was failing.
- `handleGasEstimate` now wraps all actions on a multisend, so `estimateGas` doesn't fail on cases where actions depend on each other in order for the batch tx to succeed.
None

Fix gasEstimateFromActions to use baal module as entrypoint

---

package.json
yarn.lock

https://github.com/HausDAO/monorepo/issues/368
used a workaround vs updating storybook to version 7
https://github.com/storybookjs/storybook/issues/21642
`"@storybook/react-docgen-typescript-plugin": "1.0.6--canary.9.cd77847.0"`

fixing storybook from typescript upgrade

---

libs/ui/src/components/atoms/Tag/Tag.styles.ts
libs/ui/src/components/atoms/Tag/Tag.tsx

NA
Renamed tagColor Prop to $tagColor passed to styled component to prevent it being passed to DOM
NA

fix: Renamed tagColor

---

apps/summon-safe/src/utils/txHelpers.ts
package.json
yarn.lock

None
Bump `@daohaus/baal-contracts` dependency to use the latest compatible Zodiac library version
- `@gnosis.pm/zodiac` **removed** in favour of the one used by the `@daohaus/baal-contracts` dependency

bump zodiac version

---

libs/tx-builder/src/utils/multicall.ts

None
Fix tx encoding errors when building sidecar safe proposals. This error was introduced in #364 so this PR also considers not to break the tx gas estimate process
None

fix tx lego builder for sidecar safe proposals

---

apps/admin/src/hook/walletConnect.tsx
libs/moloch-v3-fields/src/utils/walletConnect.tsx

None
The following error message is thrown when the dao tries to sign a typed message using the wallet connect proposal form:
```
primary types or unused types: "EIP712Domain", "PermitSingle" (argument="types", value={"EIP712Domain":[{"name":"name","type":"string"},{"name":"chainId","type":"uint256"},{"name":"verifyingContract","type":"address"}],"PermitSingle":[{"name":"details","type":"PermitDetails"},{"name":"spender","type":"address"},{"name":"sigDeadline","type":"uint256"}],"PermitDetails":[{"name":"token","type":"address"},{"name":"amount","type":"uint160"},{"name":"expiration","type":"uint48"},{"name":"nonce","type":"uint48"}]}, code=INVALID_ARGUMENT, version=hash/5.7.0)
```
This PR patches the intercepted message before signing.
None
Before making your PR, please check the …

Fix signTypedMessage requests on WalletConnect proposal form

---

libs/tx-builder/src/utils/overrides.ts
libs/tx-builder/src/utils/txBuilderUtils.ts
libs/utils/src/types/legoTypes.ts
libs/utils/src/utils/formatting.ts
libs/utils/src/utils/gas.ts

None
Solves an issue reported when triggering a tx on the admin app loaded as a Safe App
It also fixes the tx overrides that weren't used after the wagmi migration.
None

Fix invalid bignumber when using admin as a SafeApp

---

libs/connect-context/src/Connect.tsx
libs/utils/src/utils/gas.ts

https://github.com/HausDAO/monorepo/issues/360
wagmi has a different config then when we manually create viem clients [usign `createTransport` with manual `retryCount`](https://github.com/HausDAO/monorepo/blob/develop/libs/utils/src/utils/viem.ts#L12)
https://wagmi.sh/react/providers/configuring-chains#retrycount-optional
adding manual `retryCOunt` to configureChains so wagmi also takes the increased attempts into consideration. -- default is 3 currently

adding retry count to wagmi config

---

libs/tx-builder/src/utils/multicall.ts

Reports of failing transactions due to low gas estimates
changed the gas multiplier for our default estimate

bump up default gas buffer multiplier

---

libs/tx-builder/src/utils/txBuilderUtils.ts

fixes #415  
In the TransactionNotFoundError catch the safeTxHash and retrieve the on chain tx hash on the receipet from the Safe service. Rerun the function with the correct txhash and let it flow back into the transaction lifecycles.
NA
- [ X] Critical lint errors are resolved
- [ X] App runs locally
- [ X] App builds locally (run the build command for _any impacted package_ and check for any errors before the PR)
safe sdk docs
https://github.com/safe-global/safe-apps-sdk/tree/main/packages/safe-apps-sdk
example api endpoint
https://safe-transaction-goerli.safe.global/api/v1/multisig-transactions/0x7a42aae71eb296b74720273aa6bdcc7b0358f132eeb807e776 …

use safe sdk to get onchain tx hash from safeTxHash

---

libs/moloch-v3-macro-ui/src/components/SafeCard/SafeActionMenu.tsx

fixes #357 
Allow any connected wallet to access the Safe action menu. Not just share holding members
NA
- [ X] Critical lint errors are resolved
- [ X] App runs locally
- [ X] App builds locally (run the build command for _any impacted package_ and check for any errors before the PR)

remove member check on safes action menu, open to any connected member

---

CONTRIBUTING.MD
README.md
libs/abis/README.md
libs/connect-context/README.md
libs/connect/README.md
libs/contract-utils/README.md
libs/data-fetch-utils/README.md
libs/form-builder-base/README.md
libs/form-builder/README.md
libs/keychain-utils/README.md
libs/moloch-v3-data/README.md
libs/moloch-v3-fields/README.md
libs/moloch-v3-hooks/README.md
libs/moloch-v3-legos/README.md
libs/moloch-v3-macro-ui/README.md
libs/moloch-v3-macro-ui/src/components/ProposalDetails/ProposalDetails.tsx
libs/profile-data/README.md
libs/tx-builder/README.md
libs/ui/README.md
libs/utils/README.md

n/a
- add contribution guidelines
- updates most of the README.md
n/a

contributing draft

---

libs/moloch-v3-macro-ui/src/utils/proposalDetailsHelpers.ts

n/a
https://discord.com/channels/709210493549674598/1082758136093478932/1167231968648384512
- adds a param name to the transfer data check
n/a

transfer encoding error issue

---

libs/moloch-v3-macro-ui/src/utils/proposalDetailsHelpers.ts
libs/tx-builder/src/utils/deepDecoding.ts

None
This PR fixes the following display bugs found in ProposalDetails:
- When a proposal mint/transfer tokens to multiple recipients, it should sum up the value arrays in `getValueFromMintOrTransferAction`. Current implementation was throwing an exception.
- When a proposal decoded action has empty parameters of type array, it should display `[]` instead of `0x`.
Example proposal that display both issues can be found [here](https://admin.daohaus.fun/#/molochV3/0x5/0x52ccffa85a7d5ce76a343edca9d84acb3f191733/proposal/4)
None

Fix decoding actions with array params

---

libs/moloch-v3-fields/src/fields/MarkdownField.tsx

https://github.com/HausDAO/monorepo/issues/440
1. Added a ContentWrapper around the Dialog Content
2. DialogMarkdown Editor & Preview mode now respect that outer content
3. ContentWrapper utilises viewport width to be responsive
none

Markdown Editor & Preview respect outer container & responsive;

---

libs/tx-builder/src/utils/constants.ts
libs/tx-builder/src/utils/multicall.ts
libs/utils/src/constants/proposals.ts
libs/utils/src/utils/gas.ts

Bad gas estimates on multicall
more on #422 
adding a gas buffer on every multicall action to account for extra overhead
- [ X] Critical lint errors are resolved
- [ X] App runs locally
- [ X] App builds locally (run the build command for _any impacted package_ and check for any errors before the PR)

better gas estimation by incorporating estimated overhead for action

---

libs/moloch-v3-legos/src/tx.ts

[Reported issue](https://discord.com/channels/684227450204323876/1162312159951335475/1181449676596203540)
Fix funding proposal tx lego to set tx calldata to `0x` instead of `ENCODED_0X0_DATA`
None

Fix funding proposal tx lego

---

libs/tx-builder/src/utils/deepDecoding.ts

None
Properly display Struct type arguments on proposal decoded actions
None

fix decoding ABI params with struct type

---

libs/utils/src/constants/proposals.ts

None
aAdjust `PROCESS_PROPOSAL_GAS_LIMIT_ADDITION` constant value to 400k to account for cases when the length of `proposalData` is larger(making `hashOperation` to consume more gas)
None

Increase process proposal gaslimit addition

---

libs/moloch-v3-fields/src/fields/MultisendActions.tsx

- Potentially closing #303 although there's a separate issue for the ABI parser for proxy contracts (more sophisticated solution needed)
Allows the user to override the ABI manually

Allow tx builder ABI to be overridden

---

libs/moloch-v3-fields/src/utils/walletConnectV2.tsx

None
The `Tx type not supported` error was [reported](https://discord.com/channels/709210493549674598/1082758136093478932/1209965126539550861) when trying to use the WalletConnect proposal to catch a transaction from the Superfluid dApp. This happens as the app requests the wallet provider to estimate gas for the individual action before submitting the tx payload. In the case of the WC proposal this isn't required so it's fine to return zero
None

Fix issue when external apps request WC proposal to estimate gas

---

libs/moloch-v3-macro-ui/src/components/ProposalActionData/ProposalActionData.tsx
libs/tx-builder/src/utils/decoding.ts
libs/tx-builder/src/utils/deepDecoding.ts

None
Display contract address, calldata and value in case the app fails to decode action data. This update provides additional info for proposal validation/debugging purposes
None

Update decoding action error card for better debug info

---

libs/moloch-v3-macro-ui/src/components/ProposalCard/ProposalCardOverview.tsx

[Add a link to the GitHub issue.](https://github.com/HausDAO/monorepo/issues/451)
Added word break for long text so links and long strings will wrap instead of breaking out of the card

Fix: Long text breaks out of card

---

apps/admin/src/components/HomeDashboard.tsx
apps/summon-safe/src/utils/graphql.ts
libs/keychain-utils/src/endpoints.ts
libs/moloch-v3-fields/src/utils/fieldHelpers.ts
yarn.lock

updates endpoints and api keys

---

libs/moloch-v3-fields/src/fields/RequestERC20.tsx
libs/moloch-v3-fields/src/fields/RequestNativeToken.tsx
libs/utils/src/utils/units.ts

#444 
Fix number overflow in max button. Also removes any trailing zeroes in truncated value.
None

Fix number overflow in max button

---

apps/summon-safe/src/components/Toggle.tsx
apps/summon-safe/src/views/SummonForm.tsx

#517 
Add minor UI fixes to match the same layout as the main summoner app
None

Add minor UI fixes on summon-safe-app
